Add new parameter TARGET_UBUNTU_MIRROR to config
mvallim/live-custom-ubuntu-from-scratch pull request #36
Opened 2021-11-08 23:00 UTC by NotNorom

I used the original script today not realizing I was using a us mirror from Germany. I wanted to make these changes myself but  @sostela nailed it already.

2021-11-09 15:29 UTC, kgilmer requested changes
The config script version needs to bump so that users with older config scripts will know to take the update with the mirror defined.  See https://github.com/mvallim/live-custom-ubuntu-from-scratch/blob/master/scripts/default_config.sh#L67

2021-11-09 22:24 UTC, NotNorom commented on scripts/default_config.sh
> +export  TARGET_UBUNTU_MIRROR="http://mirrors.aliyun.com/ubuntu/"
You mean http://us.archive.ubuntu.com/ubuntu/ ?

2021-11-10 03:22 UTC, kgilmer commented on scripts/default_config.sh
> +export  TARGET_UBUNTU_MIRROR="http://mirrors.aliyun.com/ubuntu/"
Yes, that's it, thanks.

2021-11-10 03:23 UTC, kgilmer commented
@mvallim are you ok with this change?  I see no problems.

2021-11-14 19:35 UTC, kgilmer approved these changes
LGTM

2021-11-15 22:28 UTC, NotNorom commented
I'm confused was to why the build shows failing

2021-11-16 04:20 UTC, merged